version: 2
updates:
  # npm dependencies: lockfile-only strategy with grouped updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    groups:
      prod-patches:
        dependency-type: 'production'
        update-types:
          - 'patch'
      dev-minor-patch:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore(ci)'
