version: 2
updates:
  # npm: grouped updates with lockfile-only strategy
  # Trade-off: Single entry required (Dependabot doesn't allow duplicate package-ecosystem+directory)
  # Production gets patch-only; dev gets minor+patch (both groups use lockfile-only to prevent package.json churn)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    groups:
      prod-patches:
        dependency-type: 'production'
        update-types:
          - 'patch'
      dev-minor-patch:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore(ci)'
