name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  security-events: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm -w build
      - run: pnpm -w lint
      - run: pnpm -w typecheck
      - run: pnpm -w test -- --reporter=dot

  license-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - name: Fail on disallowed licenses (GPL/AGPL)
        run: |
          pnpm dlx license-checker-rseidelsohn --production --excludePackages "402kit-monorepo" --onlyAllow "MIT;ISC;BSD-2-Clause;BSD-3-Clause;Apache-2.0;CC0-1.0;Unlicense;0BSD;Python-2.0"

  vuln-scan:
    runs-on: ubuntu-latest
    continue-on-error: true # Known dev-dep vulnerabilities (esbuild, hono) accepted for now
    steps:
      - uses: actions/checkout@v5
      - uses: google/osv-scanner/actions/scanner@v2.2.3
        with:
          scan-args: '--lockfile=pnpm-lock.yaml'

  conformance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm -w build
      - run: pnpm -w test:conformance

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: anchore/sbom-action@v0.17.0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
